# -*- coding: utf-8 -*-
"""LibraryManagement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pICaVTX-s9CyGgTQmXmSyUcf9ITGBIwv
"""

# Library Management System

import os

# Create file only if it does not exist
if not os.path.exists("book1.csv"):
    file = open("book1.csv", "w")
    file.write("101,Python Basic,Saurabha Srivastava,2027\n")
    file.close()
while True:
    print("\n--------- Welcome To Suvidha Library ----------\n")
    print("1. Add Book")
    print("2. Remove Book")
    print("3. Display Books")
    print("4. Search Book")
    print("5. Exit")
    choice = int(input("\nEnter Your Choice :- "))

    # ---------------- ADD BOOK ---------------- #
    if choice == 1:
        book_id, book_name, author, year = input( "\nEnter Book Details (ID,Name,Author,Year) :- ").split(",")
        line = f"{book_id},{book_name},{author},{year}\n"
        file = open("book1.csv", "r")
        data = file.read()
        file.close()
        if line not in data:
            file = open("book1.csv", "a")
            file.write(line)
            file.close()
            print("\nBook Added Successfully.")
        else:
            print("\nBook Already Exists.")

    # ---------------- REMOVE BOOK ---------------- #
    elif choice == 2:
        book_id = int(input("\nEnter Book Id :- "))
        file = open("book1.csv", "r")
        lines = file.readlines()
        file.close()
        found = False
        new_data = []
        for line in lines:
            data = line.strip().split(",")
            # Skip header row
            if data[0] == "Book_Id":
                new_data.append(line)
                continue
            if len(data) > 1 and int(data[0]) == book_id:
                print("\nBook Found.\n")
                print("Book Id :- ", data[0])
                print("Book Name :- ", data[1])
                print("Book Author :- ", data[2])
                print("Publish Year :- ", data[3])
                found = True
                remove_choice = input("\nDo You Want To Remove This Book (y/n) :- ")
                if remove_choice.lower() == 'y':
                    print("\nBook Removed Successfully.")
                else:
                    new_data.append(line)
            else:
                new_data.append(line)
        if not found:
            print("\nBook Not Found.")
        file = open("book1.csv", "w")
        file.writelines(new_data)
        file.close()

    # ---------------- DISPLAY BOOKS ---------------- #
    elif choice == 3:
     file = open("book1.csv", "r")
     print("\n---------------- Library Books ----------------\n")
     print(
         f"{'Book ID':<10}"
         f"{'Book Name':<25}"
         f"{'Author':<25}"
         f"{'Year':<10}"
     )
     print("-" * 65)
     for line in file:
         data = line.strip().split(",")
         if data[0] == "Book_Id":
            continue
         print(
             f"{data[0]:<10}"
             f"{data[1]:<25}"
             f"{data[2]:<25}"
             f"{data[3]:<10}"
         )
     file.close()
    # ---------------- SEARCH BOOK ---------------- #
    elif choice == 4:
        book_id = int(input("\nEnter Book Id :- "))
        file = open("book1.csv", "r")
        found = False
        for line in file:
            data = line.strip().split(",")
            # Skip header row
            if data[0] == "Book_Id":
                continue
            if len(data) > 1 and int(data[0]) == book_id:
                print("\nBook Found.\n")
                print("Book Id :- ", data[0])
                print("Book Name :- ", data[1])
                print("Book Author :- ", data[2])
                print("Publish Year :- ", data[3])
                found = True
                break
        if not found:
            print("\nBook Not Found.")
        file.close()

    # ---------------- EXIT ---------------- #
    elif choice == 5:
        print("\nThank You For Coming.\n")
        break
    else:
        print("\nInvalid Choice.")